version: "3"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: "jenkins"
    restart: "on-failure"
    user: "root"
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw

#! First time login
# docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
